CREATE TABLE users (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE TABLE expenses (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Amount" numeric NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_expenses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_expenses_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);